apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-peer-authentication
  namespace: argocd
  labels:
    team: infrastructure-team
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/platform-gitops.git
    targetRevision: HEAD
    path: infrastructure/istio/peer-authentication
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: super-fortnight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
