apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  labels:
    platform: observability
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-operator
    targetRevision: 5.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
