apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: observability
spec:
  istio_namespace: istio-system

  deployment:
    accessible_namespaces:
      - "**" # Access all namespaces
    image_name: quay.io/kiali/kiali
    image_version: v1.79
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  auth:
    strategy: anonymous # Use 'openid' or 'token' for production

  external_services:
    prometheus:
      url: http://kube-prometheus-stack-prometheus.observability:9090
    tracing:
      enabled: true
      in_cluster_url: http://jaeger-query.observability:16686
      use_grpc: true
      namespace_selector: true
    grafana:
      enabled: true
      in_cluster_url: http://kube-prometheus-stack-grafana.observability:80
      url: http://localhost:3000

  server:
    web_root: /kiali

  istio_labels:
    app_label_name: app
    version_label_name: version
