apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: observability
spec:
  istio_namespace: istio-system

  auth:
    strategy: anonymous

  deployment:
    accessible_namespaces:
      - "**"

  external_services:
    prometheus:
      # IMPORTANT: this must point to your Helm Prometheus service
      url: http://prometheus-operator-server.observability.svc.cluster.local
