apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: observability
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
      - "**"
  external_services:
    prometheus:
      url: http://prometheus-server.observability.svc.cluster.local
    tracing:
      enabled: true
      provider: jaeger
      url: http://tracing-query.observability.svc.cluster.local:16686
