apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100 # 1% sampling (production-safe)
    extensionProviders:
      - name: jaeger
        zipkin:
          service: tracing-collector.observability.svc.cluster.local
          port: 9411
