apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-fortnight-observability-operators
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # SINCE OPERATORS TARGET OTHER NAMESPACES; OPT_SNW > NS_SNW  
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/platform-gitops.git
    targetRevision: HEAD
    path: argocd/infrastructure/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
