apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-telemetry
  namespace: microservices
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100.0 # 100% sampling for development
      customTags:
        environment:
          literal:
            value: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger-collector.observability:9411
        sampling: 100.0
    enablePrometheusMerge: true
