apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: super-fortnight-destination-rule
  namespace: super-fortnight
spec:
  host: "*.super-fortnight.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: LEAST_REQUEST
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
        maxRequestsPerConnection: 2

