apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: "super-fortnight-gateway"
  namespace: "super-fortnight"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.api.local"
