apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: observability-providers
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
    extensionProviders:
    - name: jaeger
      zipkin:
        service: jaeger-collector.observability.svc.cluster.local
        port: 9411
    - name: prometheus
      prometheus: {}
