apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: microservices-telemetry
  namespace: microservices
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  tracing:
  - providers:
    - name: jaeger
    randomSamplingPercentage: 100.0
  metrics:
  - providers:
    - name: prometheus
