apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.9
    helm:
      values: |
        adminUser: admin
        adminPassword: admin

        service:
          type: ClusterIP
          port: 3000

        grafana.ini:
          auth.anonymous:
            enabled: true
            org_role: Viewer

        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

