apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
  namespace: observability
spec:
  strategy: production
  collector:
    replicas: 2
    resources:
      requests:
        cpu: 500m
        memory: 512Mi

  query:
    replicas: 1

  ingester:
    replicas: 1

  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      redundancyPolicy: Single
      esIndexCleaner:
        enabled: true
        numberOfDays: 1

