apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      collector:
        otlp:
          enabled: true

