apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-resources
  namespace: argocd
  labels:
    team: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy after gateway class
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/platform-gitops.git
    targetRevision: main
    path: infrastructure/envoy-gateway
    directory:
      include: [gateway.yaml,httproute.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
