apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paper-service
  namespace: argocd
  labels:
    team: team-paper-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/platform-gitops.git
    targetRevision: HEAD
    path: k8s/paper-service
    directory:
      include: deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
