apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scissor-service
  namespace: argocd
  labels:
    team: team-scissor-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/ashutosh-18k92/scissor-service.git
    targetRevision: main
    path: k8s
    directory:
      include: deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
